### PR TITLE
Python bindings

### LINKED ISSUE #1: do not write temp file
currently a temporary file is written for transcription to happen, we should pipe the audio data to whisper directly

related https://github.com/ggerganov/whisper.cpp/issues/65

### LINKED ISSUE #2: proper python bindings
current implementation is very naive and loads a new model on every transcription by simply using subprocess

we should reference this issue https://github.com/ggerganov/whisper.cpp/issues/9 and keep a model in memory

### PR DESCRIPTION
**Pull request by JarbasAl**
closes #2 
closes #1

### CODE REVIEW

**Comment by j1nx** [comment]
I will look into adding this as x-compile package within buildroot so can't yet test it out.

However a shared library should be placed within /usr/lib/ so can that path be added as default to look for it first and then check the XDG path? Is that the right XDG path btw for libraries?

Very interesting development. Well done.

**Comment by JarbasAl** [comment]
indeed XDG does not seem right here, thats just the old path for the binary, a shared library probably belongs somewhere else...

you can define the path to it to be whatever you like in mycroft.conf btw, so just pick whatever is appropriate!

**Review by j1nx — APPROVED** [review]
UNtested as of yet but as iut is a new plugin anyway: Fine by me to merge and await user feedback in the meantime.

**Comment by JarbasAl** [comment]
could we bundle the .so library in the plugin maybe? for that we need to create one for each architecture right? arm and x86

this would make it easy to ensure a supported version is always bundled, and would allow user to replace it for updates or new platforms if wanted

**Comment by j1nx** [comment]
Bundle the SO should be possible as the libstdc++ is statistically linked within the library, however then I would make sure the architecture abbreviation is added to the link name and polled by the plugin to laod the correct one. Similar as in the old days with the precise binaries.

I am not a huge fan of it in general and in this case it also looks like the development of the library is going in a very rapid way. So you will always be behind. Or indeed like with the precise binary you download the library at startup to make sure it uses the latest and greatest.

**Pull request merged**
